name: ftrack Sync

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Sync PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 8BitJonny/gh-get-current-pr@2.1.1
        id: PR
        with:
          sha: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: node ftrack-sync.mjs
        run: |
          cd .github/scripts
          npm init -y && npm install uuid
          node ftrack-sync.mjs
        env:
          FTRACK_API_KEY: ${{ secrets.FTRACK_API_KEY }}
          PR_JSON: ${{ steps.PR.outputs.pr }}
